##########
# Stages #
##########

stages:
  - build
  - test
  - deploy

default:
  tags:
    - windows
  before_script:
    - echo "default script"
    

#########
# Build #
#########

build-job:
  stage: build
  before_script:
    - echo "Before script..."
  script:
    - echo "Starting..."
    - dir
    - echo "Build end"
  after_script:
    - echo "After script..."


########
# Test #
########

test-job:
  stage: test
  needs:
    - build-job
  script:
    - echo "Running unit tests... This will take about 10 seconds."
    - sleep 10
    - echo "Code coverage is 90%"


##########
# Deploy #
##########

deploy-job:
  stage: deploy
  needs:
    - test-job
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."